[project]
name = "modulo-06"
version = "0.1.0"
description = "Módulo 6. Patrones de diseño"
authors = [
    {name = "Alan Vazquez Velasco"}
]
license = "MIT"
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
]

[tool.poetry]
packages = [
    { include = "modulo_06", from = "src" }
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
